### ISSUE TITLE
ReusableSearchProblem should not provide a heuristic method.

### ISSUE THREAD

**Issue by afck** [TyOverby/astar#4]
If I understand correctly, ReusableSearchProblem is meant to be usable for several searches with possibly different end nodes, so it doesn't seem to make sense that it can estimate the distance from a given node to the end.

Maybe ReusableSearchProblem should have a method
    fn heuristic(&self, &N, &N) -> C
instead that gives a lower bound for the distance between two nodes.

Alternatively, astar_r could take a heuristic function as an argument.

If you agree with either of these, I'm happy to implement it.

**Comment by TyOverby** [comment]
Yeah, that makes sense; I'm doing a rewrite of this entire crate on the `rewrite` branch.  It should be finished today and I'll be sure to take this feedback!

**Comment by TyOverby** [comment]
Fixed in 98576c40f9192a453f95c3a0dda892a4de16f47e
